import { ModuleId, PosSnapshot, Product, SyncSchedule, calculateTotals } from '@corporate-pos/domain';

const iso = (base: Date, days = 0, hours = 0): string =>
  new Date(base.getTime() + days * 86400000 + hours * 3600000).toISOString();
const rut = (body: number): string => {
  let sum = 0,
    multiplier = 2;
  for (const char of String(body).split('').reverse()) {
    sum += Number(char) * multiplier;
    multiplier = multiplier === 7 ? 2 : multiplier + 1;
  }
  const check = 11 - (sum % 11);
  return `${body}-${check === 11 ? '0' : check === 10 ? 'K' : check}`;
};
export function createFixtures(now = new Date()): PosSnapshot {
  const catalog: [string, string, string, number, string][] = [
    ['Guante de trabajo reforzado', 'Seguridad', 'Atlas', 4990, 'par'],
    ['Casco de seguridad blanco', 'Seguridad', 'Atlas', 12990, 'un'],
    ['Zapato de seguridad T42', 'Seguridad', 'Meridiano', 42990, 'par'],
    ['Chaleco reflectante', 'Seguridad', 'Atlas', 6990, 'un'],
    ['Taladro percutor 750 W', 'Herramientas', 'Meridiano', 64990, 'un'],
    ['Set de brocas 19 piezas', 'Herramientas', 'Meridiano', 19990, 'set'],
    ['Llave ajustable 10 pulgadas', 'Herramientas', 'Atlas', 14990, 'un'],
    ['Destornilladores 6 piezas', 'Herramientas', 'Atlas', 9990, 'set'],
    ['Cinta métrica 5 metros', 'Herramientas', 'Meridiano', 5990, 'un'],
    ['Disco de corte 4½ pulgadas', 'Consumibles', 'Atlas', 1790, 'un'],
    ['Aceite motor sintético 1 L', 'Lubricantes', 'Horizonte', 12990, 'un'],
    ['Grasa multiuso 400 g', 'Lubricantes', 'Horizonte', 8990, 'un'],
    ['Limpiador de contactos', 'Consumibles', 'Horizonte', 7990, 'un'],
    ['Cinta aislante 20 m', 'Eléctrico', 'Atlas', 2490, 'un'],
    ['Extensión eléctrica 10 m', 'Eléctrico', 'Meridiano', 22990, 'un'],
    ['Lámpara portátil LED', 'Eléctrico', 'Meridiano', 34990, 'un'],
    ['Perno hexagonal M10 x 40', 'Fijaciones', 'Atlas', 390, 'un'],
    ['Tuerca M10 galvanizada', 'Fijaciones', 'Atlas', 190, 'un'],
    ['Pack amarras 200 mm', 'Fijaciones', 'Horizonte', 3990, 'pack'],
    ['Caja organizadora 12 pulgadas', 'Herramientas', 'Atlas', 16990, 'un'],
  ];
  const products: Product[] = catalog.map(([name, category, brand, price, unit], index) => ({
    id: `prod-${index + 1}`,
    sku: `DEMO-${String(index + 1).padStart(4, '0')}`,
    barcode: `7800000${String(index + 1).padStart(6, '0')}`,
    name,
    category,
    brand,
    price,
    cost: Math.round(price * 0.64),
    stock: [48, 22, 8, 36, 12, 54, 30, 41, 65, 240, 60, 48, 38, 120, 14, 19, 700, 850, 64, 27][index] ?? 20,
    unit,
    active: true,
    taxRate: 19,
    updatedAt: iso(now, -1),
  }));
  const companyNames = [
    'Taller Horizonte Demo',
    'Constructora Ladera Demo',
    'Servicios Río Claro Demo',
    'Logística Sendero Demo',
    'Ferretería Valle Demo',
    'Mantención Puerto Demo',
    'Ingeniería Cumbre Demo',
    'Transportes Roble Demo',
    'Obras del Sur Demo',
    'Comercial Farol Demo',
    'Servicios Pampa Demo',
    'Taller Brisa Demo',
  ];
  const customers = companyNames.map((name, index) => ({
    id: `cust-${index + 1}`,
    rut: rut(90000000 + index),
    name,
    email: `cliente${index + 1}@example.test`,
    phone: '+56 9 0000 0000',
    address: `Calle de demostración ${100 + index}`,
    city: ['Santiago', 'Valparaíso', 'Concepción'][index % 3],
    business: 'Servicios industriales · demostración',
    creditLimit: 500000 + index * 100000,
    creditUsed: index < 8 ? 100000 + index * 35000 : 0,
    creditTerms: { installments: (index % 3) + 1, periodDays: 30 },
    active: true,
    updatedAt: iso(now, -2),
  }));
  const sessionId = 'session-demo-current';
  const sales = Array.from({ length: 42 }, (_, index) => {
    const first = products[index % products.length],
      second = products[(index + 5) % products.length];
    const calculation = calculateTotals(
      [
        { productId: first.id, quantity: (index % 3) + 1, discount: 0 },
        { productId: second.id, quantity: 1, discount: 0 },
      ],
      products,
    );
    if (!calculation.ok) throw new Error(calculation.error);
    const totals = calculation.value;
    const current = index < 6;
    const customer = customers[index % customers.length];
    return {
      id: `sale-demo-${index + 1}`,
      number: `${index % 3 === 0 ? 'F' : 'B'}-${String(10001 + index)}`,
      createdAt: iso(now, current ? 0 : -Math.floor(index / 3), current ? -(index + 1) / 3 : -2),
      customerId: customer.id,
      customerName: customer.name,
      documentType: index % 3 === 0 ? ('factura' as const) : ('boleta' as const),
      ...totals,
      payments: [
        {
          id: `pay-demo-${index + 1}`,
          method:
            index % 3 === 0
              ? ('efectivo' as const)
              : index % 3 === 1
                ? ('debito' as const)
                : ('transferencia' as const),
          amount: totals.total,
          status: 'confirmed' as const,
          reference: `MOCK-${index + 1}`,
        },
      ],
      paymentStatus: 'confirmed' as const,
      roundingAdjustment: 0,
      paidTotal: totals.total,
      cashTendered: index % 3 === 0 ? totals.total : 0,
      change: 0,
      changeDisposition: 'cash' as const,
      changeAdvanceId: null,
      fiscalStatus: index < 2 ? ('pending' as const) : ('issued' as const),
      erpStatus: index < 4 ? ('pending' as const) : ('synced' as const),
      status: 'completed' as const,
      branchId: index % 5 === 0 && !current ? 'branch-2' : 'branch-1',
      cashier: 'Cajero Demo',
      sessionId: current ? sessionId : `session-demo-${Math.floor(index / 3)}`,
      idempotencyKey: `fixture-${index + 1}`,
      metadata: {},
    };
  });
  const cashSales = sales.filter(
    (sale) => sale.sessionId === sessionId && sale.payments[0].method === 'efectivo',
  );
  const openingAmount = 100000;
  const modules: [ModuleId, string, string, 'operation' | 'management' | 'platform' | 'policy'][] = [
    ['sales', 'Venta', 'Catálogo, carro, cobros y documentos.', 'operation'],
    ['cash', 'Turnos y caja', 'Apertura, arqueos, custodia y cierre.', 'operation'],
    ['collections', 'Cobranzas', 'Abonos de deuda y anticipos de clientes.', 'operation'],
    ['returns', 'Devoluciones', 'Notas de crédito y reembolsos separados.', 'operation'],
    ['masters', 'Maestros', 'Productos y clientes disponibles localmente.', 'management'],
    [
      'pricing',
      'Administrar precios y ofertas',
      'Editar condiciones comerciales. Las reglas vigentes se respetan al vender.',
      'management',
    ],
    ['reports', 'Reportería', 'Indicadores y exportaciones.', 'management'],
    ['sync', 'Sincronización', 'Programación y ejecución manual.', 'platform'],
    ['audit', 'Actividad y auditoría', 'Eventos técnicos y trazabilidad de cambios.', 'platform'],
    ['users', 'Usuarios y permisos', 'Acceso por rol y sucursal.', 'management'],
    ['branches', 'Sucursales', 'Configuración de puntos de atención.', 'management'],
    ['devices', 'Dispositivos', 'Impresoras, terminales y lectores simulados.', 'platform'],
    ['integrations', 'Integraciones', 'ERP, fiscalidad, pagos y Orsan.', 'platform'],
    ['updates', 'Actualizaciones', 'Versiones y canales de la aplicación.', 'platform'],
    ['cashPayment', 'Pago en efectivo', 'Permitir efectivo en ventas y cobranzas.', 'policy'],
    ['splitPayment', 'Pagos combinados', 'Combinar medios en una misma venta.', 'policy'],
    ['chequePayment', 'Cheques', 'Cheque con validación simulada de Orsan.', 'policy'],
    ['creditPayment', 'Crédito cliente', 'Usar cupo autorizado de una cuenta.', 'policy'],
    [
      'creditNotePayment',
      'Pago con nota de crédito',
      'Aplicar un saldo disponible de una nota emitida.',
      'policy',
    ],
    ['usdPayment', 'Pago en dólares', 'Conversión explícita con tipo de cambio de demostración.', 'policy'],
    ['advancePayment', 'Aplicar anticipos', 'Usar un anticipo disponible del mismo cliente.', 'policy'],
    ['discounts', 'Descuentos', 'Aplicar descuentos dentro del límite permitido.', 'policy'],
    [
      'offlineSales',
      'Venta sin conexión',
      'Solo efectivo con datos locales; fiscalidad y ERP pendientes.',
      'policy',
    ],
  ];
  const schedule = (minutes: number): SyncSchedule => ({
    enabled: true,
    mode: 'interval',
    intervalMinutes: minutes,
    time: '08:00',
    weekdays: [1, 2, 3, 4, 5, 6],
    timezone: 'America/Santiago',
  });
  return {
    schemaVersion: 1,
    products,
    priceRules: [
      {
        id: 'price-rule-1',
        name: 'Escala fijaciones · desde 100 unidades',
        productId: 'prod-17',
        customerId: null,
        minQuantity: 100,
        unitPrice: 350,
        enabled: true,
      },
      {
        id: 'price-rule-2',
        name: 'Condición Taller Horizonte',
        productId: 'prod-11',
        customerId: 'cust-1',
        minQuantity: 6,
        unitPrice: 11990,
        enabled: true,
      },
    ],
    customers,
    sales,
    heldSales: [],
    activeDraft: null,
    session: {
      id: sessionId,
      openedAt: iso(now, 0, -3),
      closedAt: null,
      cashier: 'Cajero Demo',
      openingAmount,
      countedAmount: null,
      expectedAmount: openingAmount + cashSales.reduce((sum, sale) => sum + sale.total, 0),
      difference: null,
      status: 'open',
      branchId: 'branch-1',
    },
    sessions: [],
    salesOrders: [
      {
        id: 'order-1',
        number: 'OV-DEMO-1001',
        customerId: 'cust-1',
        lines: [
          { productId: 'prod-1', quantity: 12, discount: 5, unitPrice: 4990 },
          { productId: 'prod-4', quantity: 6, discount: 5, unitPrice: 6990 },
        ],
        locked: true,
        deliveryMode: 'pickup',
        address: '',
        contact: 'Contacto Demo A',
        status: 'open',
        saleId: null,
      },
      {
        id: 'order-2',
        number: 'OV-DEMO-1002',
        customerId: 'cust-2',
        lines: [
          { productId: 'prod-5', quantity: 2, discount: 0, unitPrice: 64990 },
          { productId: 'prod-6', quantity: 2, discount: 0, unitPrice: 19990 },
        ],
        locked: true,
        deliveryMode: 'delivery',
        address: 'Calle de demostración 101',
        contact: 'Contacto Demo B',
        status: 'open',
        saleId: null,
      },
      {
        id: 'order-3',
        number: 'OV-DEMO-1003',
        customerId: 'cust-3',
        lines: [{ productId: 'prod-11', quantity: 6, discount: 0, unitPrice: 12990 }],
        locked: false,
        deliveryMode: 'pickup',
        address: '',
        contact: 'Contacto Demo C',
        status: 'open',
        saleId: null,
      },
    ],
    agreements: [],
    custodyDeposits: [],
    cashMovements: [
      {
        id: 'cash-opening-demo',
        sessionId,
        type: 'opening',
        amount: openingAmount,
        reason: 'Fondo inicial de demostración',
        createdAt: iso(now, 0, -3),
        actor: 'Cajero Demo',
        reference: sessionId,
      },
      ...cashSales.map((sale) => ({
        id: `cash-${sale.id}`,
        sessionId,
        type: 'sale' as const,
        amount: sale.total,
        reason: `Venta ${sale.number}`,
        createdAt: sale.createdAt,
        actor: 'Cajero Demo',
        reference: sale.id,
      })),
    ],
    receivables: customers.slice(0, 8).map((customer, index) => ({
      id: `debt-${index + 1}`,
      customerId: customer.id,
      document: `F-DEMO-${800 + index}`,
      issuedAt: iso(now, -35 + index * 2),
      dueAt: iso(now, -5 + index * 3),
      amount: 150000 + index * 35000,
      balance: 100000 + index * 35000,
      status: index < 2 ? 'overdue' : 'partial',
    })),
    collections: [],
    creditNotes: [],
    offers: [
      {
        id: 'offer-1',
        name: 'Semana de seguridad',
        productIds: ['prod-1', 'prod-2', 'prod-4'],
        discountPercent: 10,
        startsAt: iso(now, -2),
        endsAt: iso(now, 12),
        active: true,
      },
    ],
    syncJobs: [
      {
        id: 'sync-products',
        name: 'Productos y maestros',
        description: 'Actualiza la copia local del catálogo desde el ERP simulado.',
        direction: 'inbound',
        entities: 'Productos, categorías y marcas',
        status: 'success',
        progress: 100,
        records: 20,
        lastRun: iso(now, 0, -1),
        nextRun: null,
        schedule: schedule(15),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-customers',
        name: 'Clientes y crédito',
        description: 'Actualiza fichas y estado de cuenta en la base local.',
        direction: 'inbound',
        entities: 'Clientes y cuentas por cobrar',
        status: 'idle',
        progress: 0,
        records: 12,
        lastRun: iso(now, 0, -2),
        nextRun: null,
        schedule: schedule(30),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-prices',
        name: 'Precios y promociones',
        description: 'Renueva precios vigentes y campañas de la sucursal.',
        direction: 'inbound',
        entities: 'Precios y ofertas',
        status: 'success',
        progress: 100,
        records: 20,
        lastRun: iso(now, 0, -1),
        nextRun: null,
        schedule: schedule(10),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-sales',
        name: 'Ventas hacia ERP',
        description: 'Entrega ventas pendientes una vez por identificador.',
        direction: 'outbound',
        entities: 'Ventas',
        status: 'idle',
        progress: 0,
        records: 0,
        lastRun: null,
        nextRun: null,
        schedule: schedule(5),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-returns',
        name: 'Notas de crédito hacia ERP',
        description: 'Entrega las notas de crédito sin repetir las ventas.',
        direction: 'outbound',
        entities: 'Notas de crédito',
        status: 'idle',
        progress: 0,
        records: 0,
        lastRun: null,
        nextRun: null,
        schedule: schedule(5),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-collections',
        name: 'Cobranzas hacia ERP',
        description: 'Entrega abonos y anticipos de clientes.',
        direction: 'outbound',
        entities: 'Cobranzas y anticipos',
        status: 'idle',
        progress: 0,
        records: 0,
        lastRun: null,
        nextRun: null,
        schedule: schedule(5),
        failNext: false,
        lastError: null,
      },
      {
        id: 'sync-fiscal',
        name: 'Documentos fiscales',
        description: 'Emisión simulada; nunca utiliza folios reales ni envía al SII.',
        direction: 'outbound',
        entities: 'Boletas, facturas y notas de crédito',
        status: 'idle',
        progress: 0,
        records: 0,
        lastRun: null,
        nextRun: null,
        schedule: { ...schedule(5), enabled: false, mode: 'manual' },
        failNext: false,
        lastError: null,
      },
    ],
    syncRuns: [],
    outbox: [
      ...sales.slice(0, 4).map((sale) => ({
        id: `evt-${sale.id}-erp`,
        aggregateId: sale.id,
        type: 'sale.created' as const,
        target: 'erp' as const,
        status: 'pending' as const,
        attempts: 0,
        createdAt: sale.createdAt,
        deliveredAt: null,
        lastError: null,
      })),
      ...sales.slice(0, 2).map((sale) => ({
        id: `evt-${sale.id}-fiscal`,
        aggregateId: sale.id,
        type: 'sale.created' as const,
        target: 'fiscal' as const,
        status: 'pending' as const,
        attempts: 0,
        createdAt: sale.createdAt,
        deliveredAt: null,
        lastError: null,
      })),
    ],
    logs: [
      {
        id: 'log-demo-1',
        createdAt: iso(now, 0, -1),
        level: 'info',
        source: 'sync-products',
        message: 'Copia local de 20 productos actualizada.',
        correlationId: 'run-demo-products',
      },
      {
        id: 'log-demo-2',
        createdAt: iso(now, 0, -0.5),
        level: 'warning',
        source: 'outbox',
        message: 'Hay eventos de demostración pendientes de enviar.',
        correlationId: 'demo-seed',
      },
    ],
    audit: [
      {
        id: 'audit-demo-1',
        createdAt: iso(now, 0, -3),
        actor: 'Administrador Demo',
        role: 'admin',
        action: 'demo.initialized',
        entity: 'workspace',
        detail: 'Entorno local con datos sintéticos.',
      },
    ],
    devices: [
      {
        id: 'dev-printer',
        name: 'Impresora térmica · caja 01',
        type: 'printer',
        connection: 'Adaptador mock · USB',
        enabled: true,
        status: 'ready',
        lastTest: iso(now, 0, -2),
      },
      {
        id: 'dev-payment',
        name: 'Terminal de pago',
        type: 'payment',
        connection: 'Adaptador mock · Transbank',
        enabled: true,
        status: 'ready',
        lastTest: null,
      },
      {
        id: 'dev-scanner',
        name: 'Lector de códigos',
        type: 'scanner',
        connection: 'Adaptador mock · HID',
        enabled: true,
        status: 'ready',
        lastTest: null,
      },
      {
        id: 'dev-drawer',
        name: 'Gaveta de efectivo',
        type: 'drawer',
        connection: 'Adaptador mock · impresora',
        enabled: true,
        status: 'ready',
        lastTest: null,
      },
      {
        id: 'dev-cheque',
        name: 'Lector de cheques',
        type: 'cheque',
        connection: 'Adaptador mock · Orsan',
        enabled: false,
        status: 'offline',
        lastTest: null,
      },
    ],
    modules: modules.map(([id, name, description, category]) => ({
      id,
      name,
      description,
      category,
      enabled: true,
    })),
    users: [
      {
        id: 'user-admin',
        name: 'Administrador Demo',
        email: 'admin@example.test',
        role: 'admin',
        active: true,
        branchIds: ['branch-1', 'branch-2', 'branch-3'],
      },
      {
        id: 'user-supervisor',
        name: 'Supervisor Demo',
        email: 'supervisor@example.test',
        role: 'supervisor',
        active: true,
        branchIds: ['branch-1'],
      },
      {
        id: 'user-cashier',
        name: 'Cajero Demo',
        email: 'caja@example.test',
        role: 'cashier',
        active: true,
        branchIds: ['branch-1'],
      },
      {
        id: 'user-auditor',
        name: 'Auditor Demo',
        email: 'auditor@example.test',
        role: 'auditor',
        active: true,
        branchIds: ['branch-1', 'branch-2', 'branch-3'],
      },
    ],
    branches: [
      {
        id: 'branch-1',
        code: 'STG-01',
        name: 'Santiago Centro',
        city: 'Santiago',
        address: 'Avenida Demo 100',
        active: true,
        terminals: 4,
        online: true,
      },
      {
        id: 'branch-2',
        code: 'VLP-01',
        name: 'Valparaíso',
        city: 'Valparaíso',
        address: 'Calle Demo 200',
        active: true,
        terminals: 3,
        online: true,
      },
      {
        id: 'branch-3',
        code: 'CCP-01',
        name: 'Concepción',
        city: 'Concepción',
        address: 'Ruta Demo 300',
        active: true,
        terminals: 2,
        online: false,
      },
    ],
    integrations: [
      {
        id: 'int-erp',
        name: 'ERP corporativo',
        kind: 'erp',
        provider: 'Dynamics AX · mock',
        enabled: true,
        status: 'connected',
        lastTest: null,
      },
      {
        id: 'int-fiscal',
        name: 'Documentos tributarios',
        kind: 'fiscal',
        provider: 'Proveedor DTE · mock',
        enabled: true,
        status: 'connected',
        lastTest: null,
      },
      {
        id: 'int-payments',
        name: 'Pagos con tarjeta',
        kind: 'payments',
        provider: 'Transbank · mock',
        enabled: true,
        status: 'connected',
        lastTest: null,
      },
      {
        id: 'int-cheques',
        name: 'Validación de cheques',
        kind: 'cheques',
        provider: 'Orsan · mock',
        enabled: true,
        status: 'connected',
        lastTest: null,
      },
    ],
    referenceCatalogs: {
      bank: [
        { id: 'bank-1', code: 'DEMO-01', name: 'Banco de demostración A', active: true },
        { id: 'bank-2', code: 'DEMO-02', name: 'Banco de demostración B', active: true },
      ],
      plaza: [
        { id: 'plaza-1', code: 'STG', name: 'Santiago', active: true },
        { id: 'plaza-2', code: 'VLP', name: 'Valparaíso', active: true },
      ],
      returnReason: [
        { id: 'reason-1', code: 'FALLA', name: 'Producto defectuoso', active: true },
        { id: 'reason-2', code: 'CAMBIO', name: 'Cambio solicitado por cliente', active: true },
        { id: 'reason-3', code: 'ERROR', name: 'Error en documento de venta', active: true },
      ],
      seller: [
        { id: 'seller-1', code: 'V001', name: 'Vendedor Demo A', active: true },
        { id: 'seller-2', code: 'V002', name: 'Vendedor Demo B', active: true },
      ],
    },
    settings: {
      companyName: 'Comercial Atlas · Demo',
      companyRut: rut(99000000),
      branchId: 'branch-1',
      terminalId: 'CAJA-01',
      currency: 'CLP',
      taxRate: 19,
      maxDiscountPercent: 20,
      offlineLimit: 500000,
      autoPrint: true,
      receiptMessage: 'Gracias por preferirnos. Documento de demostración sin validez tributaria.',
      theme: 'light',
      sidebarCollapsed: false,
    },
    update: {
      currentVersion: '0.1.0',
      availableVersion: '0.2.0',
      channel: 'stable',
      status: 'available',
      checkedAt: null,
    },
    role: 'admin',
    online: true,
  };
}
